### PR TITLE
Bumped versions to include VS 2019 Preview.

### PR DESCRIPTION
**Pull request by leniency**
I bumped the version range to include VS 2019 (16).

So far it's been working on my machine and the 1.1 Preview with just this change.

### CODE REVIEW

**Comment by madskristensen** [comment]
It uses APIs for the HTML editor that may not be compatible. Did you test that it works and not just installs in VS 2019?

**Comment by leniency** [comment]
I've been using it this morning doing localhost development with an MVC 5 project. So perhaps not extensively tested, but so far no issues.

**Comment by duncansmart** [comment]
Works fine here too doing `CTRL+SHIFT+I` inspections

**Comment by leniency** [comment]
Inspect mode is working here still with the 2019 RC.  Debug mode though causes a full crash:

```
Exception Info: System.IO.FileNotFoundException
   at BrowserLinkInspector.DesignMode+<>c__DisplayClass5_0.<UpdateSource>b__0()
```

So, probably best not to take this PR.

**Comment by duncansmart** [comment]
The FileNotFoundException was `Could not load file or assembly 'Microsoft.Html.Editor, Version=15.0.0.0 ...` - it turns out the lib is now `Microsoft.WebTools.Languages.Html.Editor.dll` and lives in `%ProgramFiles(x86)%\Microsoft Visual Studio\2019\<Edition>\Common7\IDE\Extensions\Microsoft\Web Tools\Languages\` together with `Microsoft.WebTools.Languages.Html.dll` and `Microsoft.WebTools.Languages.Shared.dll`.

I've made a branch at https://github.com/duncansmart/BrowserLinkInspector/commits/vs2019 that uses these libs as well as using the new [VS 2019 SDK meta package](https://www.nuget.org/packages/Microsoft.VisualStudio.SDK).

It's not compatible with VS 2017 so I also changed name to "Browser Link Inspector 2019" in the manifest and changed package GUID. I don't know whether you'd want to create a new repo for it or maintain it in a branch alongside the 2017 version here...

You can test the VSIX from here: https://github.com/duncansmart/BrowserLinkInspector/releases/download/vs2019/BrowserLinkInspector.vsix

**Comment by przemekwa** [comment]
I have new installation vs 2019 and i get your VSIX from link, install and when i run project. Web essensial on chrome is working but when i choose inspector or design mode i can't  choose any element on site.

**Comment by leniency** [comment]
> I have new installation vs 2019 and i get your VSIX from link, install and when i run project. Web essensial on chrome is working but when i choose inspector or design mode i can't choose any element on site.

You might have to tell VS to enable Browser Link. Should just be able to type "Browser Link" in the VS search box and either open the Browser Link Dashboard and if it's disabled, it'll give you a link to do so.

Also with the VS 2019 release, I updated again. Matched the settings from @duncansmart 's updates as well as updated the other nuget dependencies to their release versions.

https://github.com/leniency/BrowserLinkInspector/releases/tag/0.5

Try that one for testing. My brief tests appear to be all happy.

**Comment by duncansmart** [comment]
Works here too 👍

**Comment by jabaker88** [comment]
Also testing as working

**Comment by xela-nosretap** [comment]
Just installed this, I'm running Version 16.2.0 Preview 1.0 and it doesn't seem to work any more.

I click on the inspect button in the Chrome extension, the cursor changes but the hovered element isn't displayed in VS.

**Comment by leniency** [comment]
@unabatedshagie I just updated all the packages and created a new release. I'm also installing the preview, test if I run into the same issue on the updated plugin.

**Comment by leniency** [comment]
> @unabatedshagie I just updated all the packages and created a new release. I'm also installing the preview, test if I run into the same issue on the updated plugin.

Yeah, can confirm same issue with 16.2. The inspect overlay triggers, but something is blocking the element highlight.

**Comment by Bjego** [comment]
Hey @madskristensen , Hey @leniency any updates on this PR? Is the fork from @leniency working as expected, or are there still bugs in the 2019 port?
With best regards,

**Comment by madskristensen** [comment]
@Bjego As I mentioned, the HTML editor APIs between VS2017 and 2019 are **not** compatible. A new version for VS2019 must be created to support it

**Comment by Bjego** [comment]
@madskristensen okay understood. 
I guess that your colleagues dropped that API for a good reason, maybe legacy code or what ever. Any chance to ask for a new API which could be used for this plugin? What do you think is there any chance to keep this plugin alive?
I guess we shouldn't ask for please add your dopped APIs again :).

**Comment by ckwyand** [comment]
@madskristensen Do you think there will be a new version for VS2019 created?  I use the Web Essentials chrome plugin with VS2017 with inspector support, and would like to move on to VS2019, but looks like there's no support for browser link inspector yet.    If not.. any similar alternatives you'd recommend?

**Pull request closed without merging**
